# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOVqw4ianorFRgwxFm7KV3YUetdGvExy

# Projeto de Calculadora
"""

numero1 = 'Continuar'
numero2 = 'Continuar'
operacao = 'Continuar'
sair = ('SAIR', 'Sair', 'sair')
while((numero1 or operacao or numero2) not in sair):

  # Um loop para garantir que numero1 seja um numero ou um pedido de sair
  while((numero1 not in sair) and (type(numero1) == str)):
    print("Por favor insira um número ou digite SAIR")
    numero1 = input("Digite o primeiro número: ")
    print("")
    try:
      numero1 = float(numero1)
    except ValueError:
      if(numero1 not in sair):
        print("Entrada inválida!")
        print("")

  # Caso numero1 seja um pedido de sair, a execução é encerrada
  if(numero1 in sair):
    print("Saindo da execução")
    break

  print("")
  print("+ para Adição")
  print("- para Subtração")
  print("* para multiplicação")
  print("/ para divisão")
  print("^ para potenciação")
  operacao = input("Qual operação você deseja realizar? ")
  print("")

  # Um loop para garantir que a operação seja válida
  while((operacao != '+') and (operacao != '-') and (operacao != '*') and
        (operacao != '/') and (operacao != "^") and
        (operacao not in sair)):
    print("Operação inválida!")
    print("")
    print("Por favor insira uma operação válida ou digite SAIR")
    operacao = input("Qual operação você deseja realizar? ")
    print("")

  # Caso a operação seja um pedido de sair, a execução é encerrada
  if(operacao in sair):
    print("Saindo da execução")
    break

  # Um loop para garantir que numero2 seja um numero ou um pedido de sair
  while((numero2 not in sair) and (type(numero2) == str)):
    print("Por favor insira um número ou digite SAIR")
    print(numero1, operacao, "...")
    numero2 = input("Digite o segundo número: ")
    print("")

    try:
      numero2 = float(numero2)
    except ValueError:
      if(numero2 not in sair):
        print("Entrada inválida!")
        print("")

  # Caso numero2 seja um pedido de sair, a execução é encerrada
  if(numero2 in sair):
    print("Saindo da execução")
    break


  if(operacao == '+'):
    print('O valor da operação é:', numero1 + numero2)
  elif(operacao == '-'):
    print('O valor da operação é:', numero1 - numero2)
  elif(operacao == '*'):
    print('O valor da operação é:', numero1 * numero2)
  elif(operacao =='/' and numero2 != 0):
    print('O valor da operação é:', numero1 / numero2)
  elif(operacao =='/' and numero2 == 0):
    print('Não é possível dividir por 0')
  else:
    print('O valor da operação é:', numero1 ** numero2)

  print("")

  # Redefinir as variáveis para manter o loop
  numero1 = 'Continuar'
  numero2 = 'Continuar'
  operacao = 'Continuar'